server:
  port: 9090
  context-path: /demo
spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.2.248:3306/test
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    type-aliases-package: com.example.model
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers: com.example.mapper.CommonMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
book:
  author: luxun
  name: a bloom tree
logging:
  file: D:/log/test.log
  level: DEBUG